query getManifestSubQueryCount($where: emac_manifests_bool_exp!) {
  emac_manifests_aggregate(where: $where) {
    aggregate {
      count
    }
  }
}

query getManifestSubQuery($limit: Int!, $offset: Int!, $where: emac_manifests_bool_exp!) {
  emac_manifests(
    limit: $limit
    offset: $offset
    where: $where
    order_by: { created_at: desc }
  ) {
    id
    manifest_date
    manifest_no
    note
    reference_number
    status
    wt_stt
    wr_stt
    wg_stt
    wd_stt
    message
    security_seal
    relocate_date
    type_of_service {
      id
      name
      name_short
    }
    transporter_operations {
      transporter {
        tran_name
        tran_name_lo
      }
    }
    generator {
      gen_name
      id
      gen_name_lo
      level {
        level_name_lo
        level_name
        id
      }
    }
    disposal {
      dis_name
      dis_name_lo
    }
    waste_operations_aggregate {
      aggregate {
        sum {
          weight_disposal
          weight_generator
        }
      }
    }
    expected_relocate_date
  }
}


query getManifest {
  emac_manifests {
    id
    manifest_date
    manifest_no
    note
    reference_number
    status

    security_seal
    relocate_date
    type_of_service {
      id
      name
      name_short
    }
    transporter_operations {
      transporter {
        tran_name
      }
    }
    generator {
      gen_name
    }
    disposal {
      dis_name
    }
  }
}

query getManifestApproveSubCount($where: emac_manifests_bool_exp!) {
  emac_manifests_aggregate(where: $where) {
    aggregate {
      count
    }
  }
}

query getManifestApproveSub($limit: Int!, $offset: Int!, $where: emac_manifests_bool_exp!) {
  emac_manifest_approve:emac_manifests(
    limit: $limit
    offset: $offset
    where: $where
    order_by: { created_at: desc }
  ) {
    id
    manifest_date
    manifest_no
    note
    wg_stt
    reference_number
    status
    security_seal
    relocate_date
    type_of_service {
      id
      name
      name_short
    }
    transporter_operations {
      transporter {
        tran_name
      }
    }
     generator {
      gen_name
      id
      gen_name_lo
      level {
        level_name_lo
        level_name
        id
      }
    }
    disposal {
      dis_name
    }
     waste_operations_aggregate {
      aggregate {
        sum {
          weight_disposal
          weight_generator
        }
      }
    }
  }
}

  query getManifestCPQuery {
    emac_manifests(
      where: {
        wg_stt: { _eq: 3 }
        wr_stt: { _in: [0,1] }
        wt_stt: { _eq: 3 }
        wd_stt: { _eq: 3 }
      }
    ) {
      id
      manifest_date
      manifest_no
      note
      reference_number
      status
      security_seal
      relocate_date
      wt_stt
      wr_stt
      wg_stt
      wd_stt
      type_of_service {
        id
        name
        name_short
      }
      transporter_operations {
        transporter {
          tran_name
        }
      }
      generator {
        gen_name
      }
      disposal {
        dis_name
      }
    }
  }

  query getManifestPerQuery($id: uuid!) {
    emac_manifests(where: {gen_id: {_eq: $id}}) {
      id
      created_at
      manifest_date
      manifest_no
      note
      reference_number
      status
      wt_stt
      wr_stt
      wg_stt
      wd_stt
      security_seal
      relocate_date
      type_of_service {
        id
        name
        name_short
      }
      transporter_operations {
        transporter {
          tran_name
          id
        }
      }
      waste_operations_aggregate {
        aggregate {
          sum {
            weight_disposal
            weight_generator
          }
        }
      }
      generator {
        gen_name
        id
      }
      disposal {
        dis_name
      }
    }
  }
