query getGenerator {
  emac_generators {
    custom_address
    emac_id
    email
    enterprise_no
    gen_name
    gen_name_lo
    id
    tel
    status
    objectives
    industry_type {
      type_name
      type_name_lo
      id
    }
            level {
      id
      level_name
      level_name_lo
    }
    latlng
    village {
      vill_id
      vill_name_lo
      vill_name
      district {
        dr_id
        dr_name
        dr_name_lo
        province {
          pr_id
          pr_name
          pr_name_lo
        }
      }
    }
  }
}

query getGeneratorById($id: uuid) {
  emac_generators(where: {id: {_eq: $id}}) {
    custom_address
    emac_id
    email
    enterprise_no
    gen_name
    gen_name_lo
    id
    tel
    status
    objectives
    industry_type {
      type_name
      type_name_lo
      id
    }
    level {
      id
      level_name
      level_name_lo
    }
    latlng
    village {
      vill_id
      vill_name_lo
      vill_name
      district {
        dr_id
        dr_name
        dr_name_lo
        province {
          pr_id
          pr_name
          pr_name_lo
        }
      }
    }
    wg_users {
      id
    }
    storages {
      id
    }
    manifests {
      id
    }
    catalogs {
      id
    }
  }
}


query getGeneratorNeqCount($where: emac_generators_bool_exp!) {
  emac_generators_aggregate(where: $where) {
    aggregate {
      count
    }
  }
}

query getGeneratorNeq(
  $limit: Int!
  $offset: Int!
  $where: emac_generators_bool_exp!
) {
  emac_generators(
    limit: $limit
    offset: $offset
    where: $where
    order_by: { created_at: desc }
  ) {
    custom_address
    emac_id
    email
    enterprise_no
    gen_name
    gen_name_lo
    id
    tel
    status
    objectives
    industry_type {
      type_name
      type_name_lo
      id
    }
            level {
      id
      level_name
      level_name_lo
    }
    latlng
    village {
      vill_id
      vill_name_lo
      vill_name
      district {
        dr_id
        dr_name
        dr_name_lo
        province {
          pr_id
          pr_name
          pr_name_lo
        }
      }
    }
  }
}



