query wasteCatagoriesExtendSub($status: Int) {
  emac_catalog_operations(where: {status: {_eq: $status}}) {
    cat_name
    cat_id
    cat_date
    created_at
    custom_description
    expire_date
    id
    penalize_stt
    quota_amount
    remaining_amount
    status
    summary_amount
    waste_cat_id
    waste_category {
      code
      entry_type
    }
    extension_operations {
      extended_type
      extented_time
      generator {
        gen_name_lo
        emac_id
        id
        gen_name
      }
      id
      quota_extended
      time_extended
      created_at
      updated_at
    }
    catalog {
      generator {
        gen_name
        gen_name_lo
        emac_id
        id
      }
    }
  }
}